config/routes.rb
Rails.application.routes.draw do
  resources :todos do
    member do
      post :complete
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :task, presence: true

  scope :pending, -> { where(done: false) }
  scope :done, -> { where(done: true, due_date_enum: 0) }
  scope :outdated_done, -> { where(done: true, due_date_enum: -7) }

  def due_date_description
    case due_date_enum
    when 0
      "Today"
    when 1
      "Tomorrow"
    when -1
      "Yesterday"
    else
      if due_date_enum_before_type_cast > 1
        "After #{due_date_enum} days"
      else
        "Past #{due_date_enum.abs} days"
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy, :complete]

  def index
    @done = Todo.done
    @todos = Todo.pending
  end

  def complete
    @todo.update(done: true)
  end

  def show
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
        redirect_to todos_path, notice: I18n.t("todos.notice.created")
    else
        render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @todo.update(todo_params)
      redirect_to todos_path, notice: I18n.t("todos.notice.updated")
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @todo.destroy
    redirect_to todos_path, notice: I18n.t("todos.notice.destroyed")
  end

  private

  def set_todo
    @todo = Todo.find(params[:id])

    head(:unprocessable_entity) unless @todo
  end

  def todo_params
    params.require(:todo).permit(:task)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/to_dos_helper.rb
module ToDosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCourse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= simple_form_for todo, html: { class: "todo form" } do |f| %>
  <% if todo.errors.any? %>
    <div class="error-message">
      <%= todo.errors.full_messages.to_sentence.capitalize %>
    </div>
  <% end %>

  <%= f.input :task, input_html: { autofocus: true } %>
  <%= f.submit class: "btn btn--secondary" %>
<% end %>

app/views/todos/_todo.html.erb
<div class="todo">
  <%= link_to todo.task, todo_path(todo) %>
  <div class="todo__actions">
    <%= button_to complete_todo_path(todo),
                   method: :post,
                   class: "btn btn--light" do%>
      <i class="bi bi-check-lg"></i>
      Done
    <% end %>
    <%= button_to todo_path(todo),
                   method: :delete,
                   class: "btn btn--light" do%>
      <i class="bi bi-trash-fill"></i>
      Remove
    <% end %>
    <%= link_to edit_todo_path(todo),
                 class: "btn btn--light" do%>
      <i class="bi bi-pencil"></i>
      Edit
    <% end %>
  </div>
</div>

app/views/todos/edit.html.erb
<main class="container">
<%= link_to sanitize("&larr; Back to todo"), todo_path(@todo) %>
<div class="header">
    <h1>
        Edit To Do
    </h1>
</div>

<%= render "form", todo: @todo %>
</main>

app/views/todos/index.html.erb
<main class="container">
  <div class="header">
    <h1>Todos</h1>
    <%= link_to "New task",
                new_todo_path,
                class: "btn btn--primary" %>
  </div>

  <%= render @todos %>
  <div class="header">
    <h1>Done</h1>
  </div>
  <%= render @done %>
</main>

app/views/todos/new.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to tasks"), todos_path %>

  <div class="header">
    <h1>New To Do</h1>
  </div>

  <%= render "form", todo: @todo %>
</main>

app/views/todos/show.html.erb
<main class="container">
<%= link_to sanitize("&larr; Back to tasks"), todos_path %>
<div class="header">
<h1>
Task: <%= @todo.task %>
</h1>
</div>
</main>